name: dslsale
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  bottom_picker: ^2.7.0
  time_picker_spinner_pop_up: ^2.0.0
  flutter_screenutil: ^5.9.3
  dio: ^5.4.3+1
  provider: ^6.1.2
  no_context_navigation: ^3.0.0
  shared_preferences: ^2.2.3
  sunmi_printer_plus: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: phetsarath_ot.ttf
      fonts:
        - asset: "assets/fonts/phetsarath_ot.ttf"
